- hosts: localhost
  vars_files:
    - vars/values.yml
  tasks:
  - name: Download Java
    get_url:
      url: http://cdn-files.evildayz.com/mirror/java/jdk_7u79/jdk-7u79-linux-x64.rpm
      dest: /tmp/jdk-7u79-linux-x64.rpm
  - name: Install package.
    yum:
       name: /tmp/jdk-7u79-linux-x64.rpm
       state: present
  - name: Set path of Java
    lineinfile:
        path: ~/.bashrc
        line: "\nexport JAVA_HOME=/usr/java/jdk1.7.0_79\nexport PATH=/usr/java/jdk1.7.0_79/bin/:$PATH"
  - name: Download hadoop
    get_url:
      url: https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
      dest: /tmp/hadoop-1.2.1-1.x86_64.rpm
  - name: Install package
    command: rpm -ivh /tmp/hadoop-1.2.1-1.x86_64.rpm --replacefiles
    tags:
       - hadoop-install
  - selinux:
      policy: targeted
      state: permissive
    tags:
       - selinux
#Configure client
  - name: "Namenode Tasks: Test for core configuration"
    shell: 'grep "fs.default.name" /etc/hadoop/core-site.xml'
    args:
        executable: /bin/bash
    register: test_grep1
    ignore_errors: true
  - name: "Configuring core-site.xml"
    blockinfile:
        path: /etc/hadoop/core-site.xml
        insertafter: "<configuration>"
        content: |
                <property>
                <name>fs.default.name</name>
                <value>hdfs://{{master_ip}}:9001</value>
                </property>
    when: test_grep1.stdout == ""
  - name: Test for mapred configuration
    shell: 'grep "mapred.job.tracker" /etc/hadoop/mapred-site.xml'
    args:
        executable: /bin/bash
    register: test_grep
    ignore_errors: true
  - name: Configuring mapred-site.xml
    blockinfile:
        path: /etc/hadoop/mapred-site.xml
        insertafter: "<configuration>"
        content: |
                <property>
                <name>mapred.job.tracker</name>
                <value>{{jobtracker_ip}}:9002</value>
                </property>
    when: test_grep.stdout == ""
